### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by reedy** [ldenisey/idea-openscad#116]
**Describe the bug**
PyCharm error when viewing using the plugin to view files

**To Reproduce**

**Code snippet**
n/a

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Jetbrains platform and version: 
 ```
PyCharm 2024.2.3 (Professional Edition)
Build #PY-242.23339.19, built on September 25, 2024
Licensed to MediaWiki / Sam Reed
Subscription is active until April 1, 2025.
For non-commercial open source development only.
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.7
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ml.llm (242.23339.40)
  com.javampire.idea-openscad (2.4.0)
  com.jetbrains.space (242.23339.11)
```
 - OpenSCAD plugin version: Version 2.4.0

**Additional context**
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.javampire.openscad.action.OpenAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.javampire.idea-openscad]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by Fonant** [comment]
Same here in PhpStorm.
