### ISSUE TITLE
NotNull exception creating new Python projects in PyCharm while this plugin is installed

### ISSUE THREAD

**Issue by ali1234** [ldenisey/idea-openscad#64]
**Describe the bug**
After installing this plugin in PyCharm, I can no longer create new projects. It crashes during creation of the default project files, leaving a half setup project.

**To Reproduce**
1. Install plugin in PyCharm
2. File -> New Project
3. Select Pure Python and leave the default
4. Create in new window

**Code snippet**
N/A

**Expected behavior**
Creating a new project should succeed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Jetbrains platform and version: PyCharm Professional  2022.3
 - OpenSCAD plugin version: 2.3.2

**Additional context**
Add any other context about the problem here, error messages, stacktrace, ...

```
com.intellij.util.indexing.impl.MapReduceIndexMappingException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/psi/stubs/ObjectStubTree$StubIndexSink.occurrence must not be null
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:207)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:159)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:125)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:308)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:176)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:253)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:62)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:21)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:284)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:62)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:28)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateIndexInNonCancellableSection(FileBasedIndexImpl.java:1047)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocument$16(FileBasedIndexImpl.java:1021)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:653)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocument(FileBasedIndexImpl.java:1009)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:182)
	at com.intellij.util.indexing.RegisteredIndexes$DocumentUpdateTask.doProcess(RegisteredIndexes.java:173)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$indexUnsavedDocuments$15(FileBasedIndexImpl.java:976)
	at com.intellij.util.indexing.StorageBufferingHandler.runUpdate(StorageBufferingHandler.java:22)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:976)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:810)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:305)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:71)
	at com.intellij.psi.stubs.StubIndexEx.getAllKeys(StubIndexEx.java:293)
	at com.intellij.lang.javascript.psi.stubs.JSUsedRemoteModulesIndex.getUsedModules(JSUsedRemoteModulesIndex.java:34)
	at com.intellij.lang.javascript.modules.remote.JSRemoteModulesUsagesDetector.findAllUsedModules(JSRemoteModulesUsagesDetector.java:66)
	at com.intellij.lang.javascript.modules.remote.JSRemoteModulesUsagesDetector.updateModulesSnapshot(JSRemoteModulesUsagesDetector.java:111)
	at com.intellij.lang.javascript.modules.remote.JSRemoteModulesUsagesDetector.lambda$performNonBlockingUpdate$0(JSRemoteModulesUsagesDetector.java:98)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/psi/stubs/ObjectStubTree$StubIndexSink.occurrence must not be null
	at com.intellij.psi.stubs.ObjectStubTree$StubIndexSink.$$$reportNull$$$0(ObjectStubTree.java)
	at com.intellij.psi.stubs.ObjectStubTree$StubIndexSink.occurrence(ObjectStubTree.java)
	at com.javampire.openscad.psi.stub.OpenSCADModuleStubElementType.indexStub(OpenSCADModuleStubElementType.java:54)
	at com.javampire.openscad.psi.stub.OpenSCADModuleStubElementType.indexStub(OpenSCADModuleStubElementType.java:15)
	at com.intellij.psi.stubs.ObjectStubTree.indexStubTree(ObjectStubTree.java:57)
	at com.intellij.psi.stubs.SerializedStubTree.indexTree(SerializedStubTree.java:191)
	at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:60)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:196)
	... 65 more
```

**Comment by ldenisey** [comment]
Hello,
I have tried with PyCharm 2023.3.2 (Build #PY-233.13135.95), plugin version 2.4.0 and haven't got the issue.
Can you retry on your side and tell me if you still have the issue ?
